const Complex = require('./index.js')
const cpx1 = new Complex(4, 3)
const cpx2 = new Complex(6, 8)
console.log(cpx1.plus(cpx2).mathForm())
console.log(cpx1.minus(cpx2).mathForm())
console.log(cpx1.times(cpx2).mathForm())
console.log(cpx1.divide(cpx2).mathForm())
console.log(cpx1.toAbs())
console.log(cpx1.toConj().mathForm())
